# Created by Jekyll Writer
title: TangXiaoLv
baseurl: /Blog
url: ''
email: imbatang@gmail.com | imbatang@126.com
kramdown:
  input: GFM
permalink: pretty
google_analytics: null
disqus_shortname: null
